<?php
// module/Album/view/album/album/add.phtml:

$title = 'Edit category';
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('category', ['action' => 'edit']));//$this->url('document/category', ['action' => 'create']));
$form->setAttribute('name', 'editCategoryForm');
$form->prepare();

echo $this->form()->openTag($form); ?>
<div class="form-group">
<?= $this->formRow($form->get('name')) ?>
</div>
<?= $this->formSubmit($form->get('submit')) ?>
<?= $this->form()->closeTag() ?>