<?php
// module/Album/view/album/album/add.phtml:

$title = 'Change permission';
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', '/document/category/permission');//$this->url('document/category', ['action' => 'create']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('upload'));
echo $this->formRow($form->get('download'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
