<?php
// module/Album/view/album/album/add.phtml:

$title = 'Change permission';
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('category', ['action' => 'permission','id'=>$cid]));
$form->prepare();

echo $this->form()->openTag($form); ?>
<div class="form-group">
<?= $this->formRow($form->get('upload')) ?>
</div>
<div class="form-group">
<?= $this->formRow($form->get('download')) ?>
</div>
<?= $this->formSubmit($form->get('submit')) ?>
<?= $this->form()->closeTag() ?>

