<button class="btn btn-default"id="createSubCategory">Create sub category</button>
<button class="btn btn-default" id="createRootCategory">Create root category</button>
<button class="btn btn-default" id="editCategory">Edit category name</button>
<button class="btn btn-default" id="changePermission">Change permission</button>
<button class="btn btn-danger" id="deleteCategory" data-confirm>Delete category</button>
<button class="btn btn-default" id="uploadFile">Upload File</button>
<p class="boxName">Categories</p>
<div id="categories">
</div>
<p class="boxName">Files</p>
<div class="infoTable">
<div class="infoTableRow">
    <div id="categoryName"></div>
    <div id="helper"></div>
</div>
<div class="infoTableRow fileInfo">
    File saved name: <div id="visibleName">-</div></br>
    File uploaded name: <div id="fileName">-</div></br>
    Version number: <div id="versionNumber">-</div></br>
    Uploaded: <div id="uploadedTime">-</div></br>
    User: <div id="uploadedUser">-</div></br>
</div>
</div>
<div id="files">
</div>
