<?php
// module/Album/view/album/album/add.phtml:

$title = 'Upload file';
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php

$form->setAttribute('action', $this->url('file', ['action' => 'upload','id'=>$cid]));
$form->prepare();
?>

<?= $this->form()->openTag($form) ?>
<div class="form-group">
<?= $this->formRow($form->get('fileName'))?>
</div>
<div class="form-group">
<?= $this->formRow($form->get('file'))?>
</div>
<?= $this->formSubmit($form->get('submit'))?>
<?= $this->form()->closeTag()?>
